/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqlbasesdedatos.Interfaz;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class RegistroProducto extends javax.swing.JFrame {

    /**
     * Creates new form RegistroProducto
     */
    public RegistroProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPr = new javax.swing.JPanel();
        codenamelabel = new javax.swing.JLabel();
        titlelbl = new javax.swing.JLabel();
        usrIcon = new javax.swing.JLabel();
        codenametxt = new javax.swing.JTextField();
        corePanel = new javax.swing.JPanel();
        l2sizelbl = new javax.swing.JLabel();
        l1sizelbl = new javax.swing.JLabel();
        corecountlbl = new javax.swing.JLabel();
        corecountCombo = new javax.swing.JComboBox<>();
        l2sizecombo = new javax.swing.JComboBox<>();
        l1sizecombo1 = new javax.swing.JComboBox<>();
        freqlbl = new javax.swing.JLabel();
        freqtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        techlbl = new javax.swing.JLabel();
        lithcombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        uarchcombo = new javax.swing.JComboBox<>();
        isPrivateBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPr.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        codenamelabel.setText("Codename");

        titlelbl.setText("Registrar Producto");

        usrIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlbasesdedatos/Misc/soc.png"))); // NOI18N
        usrIcon.setText("ProdIcon");

        codenametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codenametxtActionPerformed(evt);
            }
        });

        corePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        l2sizelbl.setText("Tamaño Cache L2");

        l1sizelbl.setText("Tamaño Cache L1");

        corecountlbl.setText("Nucleos");

        corecountCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "6", "8", "10" }));
        corecountCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corecountComboActionPerformed(evt);
            }
        });

        l2sizecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.5MB", "1MB", "2MB", "3MB", "4MB", "8MB" }));
        l2sizecombo.setSelectedIndex(2);

        l1sizecombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8KB", "16KB", "32KB", "64KB" }));
        l1sizecombo1.setSelectedIndex(2);

        freqlbl.setText("Frecuencia");

        jLabel1.setText("Mhz");

        techlbl.setText("Litografía");

        lithcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "28nm", "20nm", "16nm", "14nm", "10nm" }));

        jLabel3.setText("uArch");

        uarchcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cortex A53", "Cortex A55", "Cortex A57", "Cortex A72", "Cortex A73", "Cortex A75" }));

        isPrivateBox.setText("Diseño privado?");

        javax.swing.GroupLayout corePanelLayout = new javax.swing.GroupLayout(corePanel);
        corePanel.setLayout(corePanelLayout);
        corePanelLayout.setHorizontalGroup(
            corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corePanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corePanelLayout.createSequentialGroup()
                        .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(corePanelLayout.createSequentialGroup()
                                .addComponent(l1sizelbl)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(corePanelLayout.createSequentialGroup()
                                .addComponent(freqlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19)))
                        .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(freqtxt)
                            .addComponent(l1sizecombo1, 0, 93, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(corePanelLayout.createSequentialGroup()
                        .addComponent(corecountlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(corecountCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(isPrivateBox))
                    .addGroup(corePanelLayout.createSequentialGroup()
                        .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l2sizelbl)
                            .addComponent(techlbl)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uarchcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l2sizecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lithcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        corePanelLayout.setVerticalGroup(
            corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corecountCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corecountlbl)
                    .addComponent(isPrivateBox))
                .addGap(18, 18, 18)
                .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(freqlbl)
                    .addComponent(freqtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1sizelbl)
                    .addComponent(l1sizecombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l2sizelbl)
                    .addComponent(l2sizecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techlbl)
                    .addComponent(lithcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(uarchcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Especificaciones");

        exitBtn.setText("Salir");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrLayout = new javax.swing.GroupLayout(panelPr);
        panelPr.setLayout(panelPrLayout);
        panelPrLayout.setHorizontalGroup(
            panelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrLayout.createSequentialGroup()
                .addGroup(panelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitBtn)
                    .addGroup(panelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPrLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(usrIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(panelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titlelbl)
                                .addGroup(panelPrLayout.createSequentialGroup()
                                    .addComponent(codenamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(codenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(panelPrLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabel2))
                        .addGroup(panelPrLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(corePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelPrLayout.setVerticalGroup(
            panelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usrIcon)
                    .addGroup(panelPrLayout.createSequentialGroup()
                        .addComponent(titlelbl)
                        .addGap(18, 18, 18)
                        .addGroup(panelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codenamelabel)
                            .addComponent(codenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(corePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void corecountComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corecountComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corecountComboActionPerformed

    private void codenametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codenametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codenametxtActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codenamelabel;
    private javax.swing.JTextField codenametxt;
    private javax.swing.JPanel corePanel;
    private javax.swing.JComboBox<String> corecountCombo;
    private javax.swing.JLabel corecountlbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel freqlbl;
    private javax.swing.JTextField freqtxt;
    private javax.swing.JCheckBox isPrivateBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> l1sizecombo1;
    private javax.swing.JLabel l1sizelbl;
    private javax.swing.JComboBox<String> l2sizecombo;
    private javax.swing.JLabel l2sizelbl;
    private javax.swing.JComboBox<String> lithcombo;
    private javax.swing.JPanel panelPr;
    private javax.swing.JLabel techlbl;
    private javax.swing.JLabel titlelbl;
    private javax.swing.JComboBox<String> uarchcombo;
    private javax.swing.JLabel usrIcon;
    // End of variables declaration//GEN-END:variables
}
